import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { ThemeProvider } from "./DarkModeProvider";
import DarkLightToggle from "@/components/shadCn/DarkLightToggle";
import Login from "@/components/authentication/Login";
import { auth } from "@/auth";
import SessionProvider from "../app/Providers";
import Link from "next/link";
import { connectToMongoDB } from "@/lib/db";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
   await connectToMongoDB();
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex items-center justify-end border-b border-secondary-foreground gap-4 mr-4 h-20 px-10">
              <Link className="hover:text-blue-700 transition-all duration-150" href="/dashboard">Dashboard</Link>
              <Login />
              <DarkLightToggle />
            </div>
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
